#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import SNV as snv

def append_gene_len(df,gene_table):
    """Appends gene length to SNV table
    
    DEPRECATED. anvi-gen-variability-profile now generates this column
    
    Appends gene length to each snv (row) in the SNV table.
    
    Attributes
    ----------
    df : pandas DataFrame
        SNV table that the gene length will be appended to
    gene_table : pandas DataFrame, str
        Either filepath to gene table generated by anvio (name is by default
        "{user_input}_gene-calls.txt"), or a gene table that has already been 
        loaded as a pandas DataFrame object via SNV.load_gene_table(...). if 
        filepath is provided the gene table will loaded via 
        SNV.load_gene_table(...)
        
    Returns
    -------
    df : pandas DataFrame
        The SNV table with gene_length added as one of the columns.
    """
    
#   loads gene_table as pandas DataFrame if filepath provided
    if type(gene_table) == str:
        gene_table = snv.load_gene_table(gene_table)
        
    if any(df["corresponding_gene_call"] == -1):
        raise ValueError(("Some SNVs do not belong to a gene call. Filter "
                          "out these SNVs with filter_by_snv(filt_nongene=True) "
                          "or fix this code to attribute such SNVs a gene length of -1 or 0."))

    df["gene_length"] = df["corresponding_gene_call"].apply(lambda x: \
                                                      gene_table.ix[x,'stop']-\
                                                      gene_table.ix[x,'start'])
    print("gene_length column has been added/overwritten")
    
    return df 
