import pandas as pd
import variants.snv
import re
import numpy as np

def gen_samples_of_interest_by_coverage(mean_cov_file, threshold):
    """
    Outputs .txt file of sample names for samples that have mean coverage
    above a threshold value.
    
    INPUTS
    ------
    mean_cov_file : string
        filepath of the mean coverage text file generated by anvi-summarize. The
        default name is either {collection}-mean_coverage.txt or 
        {collection}-mean_coverage_Q2Q3.txt.
    threshold : integer
        all samples with a mean coverage value below threshold will not be
        included in the output file

    OUTPUT
    ------
    outputs samples_of_interest_gt{threshold}x.txt to the same folder as 
    {collection}-mean_coverage.txt, in the format accepted by the
    anvi-gen-varability-profile flag --samples-of-interest
    """

    df = snv.read_sample_coverage(mean_cov_file,thresh=threshold,save=True)
    cols = df.columns.values
    df_names = df[cols[0]]

    print("{}\n\nsamples retained are above.".format(df))

#   some regex to get string of directory of mean_cov_file
    ind = [match for match in re.finditer(r"/",mean_cov_file)][-1].start()+1
    out = mean_cov_file[:ind]+"samples_of_interest_gt{}x.txt".format(threshold)
    df_names.to_csv(out,index=False)

    print("list of names saved to {}".format(out))
